---
title: "Instacart Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    source_code: embed
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
library(shiny)
library(rsconnect)
```


```{r read and load data, message= FALSE, warning= FALSE, echo=FALSE}
instacart = read_csv("./data_hw6/instacart_train_data.csv.zip") %>%
    clean_names()
```

```{r department donut chart analysis}
department_items_ordered_data = summarize(group_by(instacart, department),n = n()) %>% 
  arrange(desc(n)) %>% 
  rename(number_of_item_ordered = n)

```

```{r data analysis order hour for items from the household department}
household_data = 
  filter(instacart,department == "household") %>%
  select(department, order_dow, order_hour_of_day) %>%
  arrange(order_hour_of_day)
```


```{r analysis c}
aisle_tidy_data =
  instacart %>%
  select(aisle, order_hour_of_day, department) %>%
  group_by(aisle, order_hour_of_day) %>%
  summarize(n = n()) %>%
  ungroup()
```


Column {.sidebar}
-----------------------------------------------------------------------

Chart A:
```{r slider input widget}
## sliderInput widget
renderUI({
  max_number_of_item_ordered = 
    department_items_ordered_data %>%
    select(number_of_item_ordered) %>% 
    distinct(number_of_item_ordered) %>% 
    max() %>% 
    as.numeric()
  
  min_number_of_item_ordered = 
    department_items_ordered_data %>%
    select(number_of_item_ordered) %>% 
    distinct(number_of_item_ordered) %>% 
    min() %>% 
    as.numeric()
  
sliderInput("number_of_item_ordered_range", label = h3("Choose the number of ordered  items range"), min = min_number_of_item_ordered, max = max_number_of_item_ordered, value = c(1359, 409087))
})

```

Chart B:
```{r checkboxinput widget}

order_dates = instacart %>%
  arrange(order_dow) %>% 
  distinct(order_dow) %>% 
  pull()

checkboxGroupInput("order_date_choice", label = h3("Select Day"), 
    choices = order_dates, selected = 1)

            
```

Chart C:
```{r selectinput widget}

aisles = instacart %>% arrange(aisle) %>% distinct(aisle) %>% pull()

# selectInput widget
selectInput("aisle_choice", label = h3("Select aisle"),
            choices = aisles)

            
```


Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
    department_items_ordered_data %>% 
    filter(number_of_item_ordered %in% input$number_of_item_ordered_range[1]:input$number_of_item_ordered_range[2]) %>%
    mutate(text_label = str_c("Number of Items Ordered:", number_of_item_ordered)) %>%
    plot_ly(labels = ~department, values = ~number_of_item_ordered) %>% 
    add_pie(hole = 0.4) %>% 
    layout(title = "The Number of Items Ordered within Each Department", showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE), 
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

  
})


```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  fit <- density(household_data$order_hour_of_day)
  household_plot =
  household_data %>%
    filter(order_dow == input$order_date_choice) %>% 
    plot_ly(x = ~order_hour_of_day, type = "histogram", name = "Frequency") %>%
    add_trace(x = fit$x, y = fit$y, type= "scatter", mode = "lines", fill = "tozeroy", yaxis = "y2", name = "Density") %>%
    layout(yaxis2 = list(overlaying = "y", side = "right")) %>%
    layout(title = "The Hour of the Day on which the Order was placed for Household Department",
         xaxis = list(title = "Order hour of the day"), 
         yaxis = list(title = "Frequency"))
})

```

### Chart C

```{r}
renderPlotly({
  aisle_tidy_data %>%
    filter(aisle == input$aisle_choice) %>% 
    plot_ly(x = ~order_hour_of_day, y = ~n, 
          split = ~aisle, type = 'scatter', mode = 'lines') %>%
    layout(title = "The Association of Order Hour and Frequency for Different Aisles",
         xaxis = list(title = "Order hour of day", zeroline = F),
         yaxis = list(title = "Frequency", zeroline = F),
         autosize = TRUE)
})
```




